/***************************************************************************
* Create the object of Photo objects for image sets                        *
* 1,,,,,,,,,,,,,,,,,,,,,1,1,,,,,,,,,,,,,,,,,,,,,,1,,1,,,,,,,,,,,,,,,,,,,,, *
* ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,,,4,1,,,,,,,,,,,,,,,,, *
* ,,,,,,,,,,,,,,,,,,,,,,                                                   *
***************************************************************************/
if(!('backgrounds' in window)){	window.backgrounds = {};
}	backgrounds[14893426] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"2._Carloway_Crofts1.jpg","photo_ref":"","section_code":"","takendate":"","width":750,"gallery":0,"height":545,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14893426,"photographer":"","caption":"2. Carloway Crofts","item_price":"","home":0});
		backgrounds[14923297] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Seann_Taigh_Niall_oil_on_board_400x400mm.JPG","photo_ref":"","section_code":"","takendate":"","width":749,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923297,"photographer":"","caption":"Seann Taigh Niall oil on board 400x400mm","item_price":"","home":0});
		backgrounds[14937747] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"First_Flowers_of_Spring_on_the_Croft_cropped_1.jpg","photo_ref":"","section_code":"","takendate":"","width":750,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14937747,"photographer":"","caption":"First Flowers of Spring on the Croft cropped","item_price":"","home":0});
		backgrounds[14923298] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Catching_the_morning_light_cropped.jpg","photo_ref":"","section_code":"","takendate":"","width":750,"gallery":0,"height":748,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923298,"photographer":"","caption":"Catching the morning light cropped","item_price":"","home":0});
		backgrounds[14923590] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Towards_the_Morning_Light_oil_on_canvas_700x700mm.JPG","photo_ref":"","section_code":"","takendate":"","width":746,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923590,"photographer":"","caption":"Towards the Morning Light oil on canvas 700x700mm","item_price":"","home":0});
		backgrounds[14923291] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Moonlight_on_Benside_oil_on_canvas_700x700mm.JPG","photo_ref":"","section_code":"","takendate":"","width":748,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923291,"photographer":"","caption":"Moonlight on Benside (oil on canvas) 700x700mm","item_price":"","home":0});
		backgrounds[14923299] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"A_new_day_dawning_oil_on_canvas_500x500mm.JPG","photo_ref":"","section_code":"","takendate":"","width":750,"gallery":0,"height":734,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923299,"photographer":"","caption":"A new day dawning oil on canvas 500x500mm","item_price":"","home":0});
		backgrounds[14923595] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Washing_Day_at_Lilac_Cottage_oil_on_canvas_700x700mm.JPG","photo_ref":"","section_code":"","takendate":"","width":740,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923595,"photographer":"","caption":"Washing Day at Lilac Cottage (oil on canvas) 700x700mm","item_price":"","home":0});
		backgrounds[14937749] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Fresh_Blooms_after_the_Rain_oil_on_canvas_500x700mm_1.JPG","photo_ref":"","section_code":"","takendate":"","width":536,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14937749,"photographer":"","caption":"Fresh Blooms after the Rain (oil on canvas) 500x700mm","item_price":"","home":0});
		backgrounds[14923300] = clik.newPhoto({"galleries_id":"","location":"","server_id":68,"src":"Pinks_in_the_Warming_Sun.JPG","photo_ref":"","section_code":"","takendate":"","width":748,"gallery":0,"height":750,"purchase_instruction":"","description":"","payment_groups_id":"","link":"#","id":14923300,"photographer":"","caption":"Pinks in the Warming Sun","item_price":"","home":0});
		
